/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Fan `query` out to the enabled sources; stream one SSE `result` event per source,
         *     then a final `done` event. A source that errors emits a `result` with status `error`
         *     — it never breaks the stream for the others.
         */
        post: operations["search_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdapterResult
         * @description One source's outcome for one search — the unit the orchestrator streams.
         */
        AdapterResult: {
            /** Source */
            source: string;
            /** Display Name */
            display_name: string;
            status: components["schemas"]["AdapterStatus"];
            /** Records */
            records?: components["schemas"]["InmateRecord"][];
            /** Total */
            total?: number | null;
            /** Duration Ms */
            duration_ms: number;
            /** Error */
            error?: string | null;
        };
        /**
         * AdapterStatus
         * @enum {string}
         */
        AdapterStatus: "ok" | "no_results" | "error" | "timeout";
        /** Charge */
        Charge: {
            /** Offense */
            offense?: string | null;
            /** Case No */
            case_no?: string | null;
            /** Warrant No */
            warrant_no?: string | null;
            /** Disposition */
            disposition?: string | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InmateRecord */
        InmateRecord: {
            /** Source */
            source: string;
            /** Source Url */
            source_url?: string | null;
            /** Name */
            name: string;
            /** Year Of Birth */
            year_of_birth?: string | null;
            /** Sex */
            sex?: string | null;
            /** Booking Date */
            booking_date?: string | null;
            /** Photo Base64 */
            photo_base64?: string | null;
            /** Charges */
            charges?: components["schemas"]["Charge"][];
            /** Matched On */
            matched_on?: components["schemas"]["MatchInfo"][];
            /** Raw */
            raw?: {
                [key: string]: unknown;
            };
        };
        /** MatchInfo */
        MatchInfo: {
            type: components["schemas"]["MatchType"];
            /** Detail */
            detail?: string | null;
        };
        /**
         * MatchType
         * @description WHY a row matched the query — lets the UI surface real-name hits and hide
         *     attorney/alias noise. Tagging this correctly per source is the adapter's job.
         * @enum {string}
         */
        MatchType: "name" | "alias" | "attorney" | "other";
        /**
         * SearchQuery
         * @description The normalized search input.
         *
         *     `last` is the only required field — every source searches by surname. The
         *     optional fields refine the search where a source's form supports them, and are
         *     used to rank/filter results client-side where it doesn't. (Government search
         *     fields are dirty — e.g. Dallas DOB is often masked — so we prefer searching
         *     broad and ranking, over pushing filters into each site. See docs/ARCHITECTURE.)
         */
        SearchQuery: {
            /** Last */
            last: string;
            /** First */
            first?: string | null;
            /** Middle */
            middle?: string | null;
            sex?: components["schemas"]["Sex"] | null;
            /** Year Of Birth */
            year_of_birth?: number | null;
            /**
             * Max Results
             * @default 25
             */
            max_results: number;
        };
        /**
         * Sex
         * @enum {string}
         */
        Sex: "M" | "F" | "U";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_api_search_post: {
        parameters: {
            query?: {
                staff?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdapterResult"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
